# Generated by Django 5.1.2 on 2024-11-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='reward_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
