# Generated by Django 5.1 on 2024-12-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_tokensmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokensModel',
        ),
    ]
