# Generated by Django 5.1.2 on 2024-11-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Makeover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
