# Generated by Django 5.1.2 on 2024-11-04 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Makeover', '0002_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount',
            new_name='discount_percent',
        ),
    ]
