# Generated by Django 5.1.2 on 2024-11-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Makeover', '0003_rename_discount_product_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
