# Generated by Django 5.1.2 on 2024-11-04 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Makeover', '0004_alter_product_discount_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='primaryImage',
            new_name='primary_image',
        ),
    ]
