# Generated by Django 5.1.2 on 2024-11-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Makeover', '0005_rename_primaryimage_product_primary_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='short_name',
        ),
        migrations.AddField(
            model_name='product',
            name='full_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
